BHBC-2215: Update Project Role permissions for API
bcgov/biohubbc pull request #1003
Opened 2023-04-14 00:05 UTC by AlfredRosenthal

# Overview

## Links to Jira tickets

[BHBC-2215](https://quartech.atlassian.net/browse/BHBC-2215?atlOrigin=eyJpIjoiYjYxZmMzZjA1YzcwNDFhZjliNmU1NDg3M2RlZTg2MjUiLCJwIjoiaiJ9)

## Description of relevant changes

- {List all relevant changes, in particular anything that will help the reviewers test/verify this PR}

## PR Checklist

A list of items that are good to consider when making any changes.

_Note: this list is not exhaustive, and not all items are always applicable._

### Code

- [ ] New files/classes/functions have appropriately descriptive names and comment blocks to describe their use/behaviour
- [ ] I have avoided duplicating code when possible, moving re-usable pieces into functions
- [ ] I have avoided hard-coding values where possible and moved any re-usable constants to a constants file
- [ ] My code is as flat as possible (avoids deeply nested if/else blocks, promise chains, etc)
- [ ] My code changes account for null/undefined values and handle errors appropriately
- [ ] My code uses types/interfaces to help describe values/parameters/etc, help ensure type safety, and improve readability

### Style

- [ ] My code follows the established style conventions
- [ ] My code uses native material-ui components/icons/conventions when possible

### Documentation

- [ ] I have commented my code sufficiently, such that an unfamiliar developer could understand my code
- [ ] I have added/updated README's and related documentation, as needed

### Tests

- [ ] I have added/updated unit tests for any code I've added/updated
- [ ] I have added/updated the Postman requests/tests to account for any API endpoints I've added/updated

### Linting/Formatting

- [ ] I have run the linter and fixed any issues, as needed  
       _See the `lint` commands in package.json_
- [ ] I have run the formatter and fixed any issues, as needed  
       _See the `format` commands in package.json_

### SonarCloud

- [ ] I have addressed all SonarCloud Bugs, Vulnerabilities, Security Hotspots, and Code Smells

2023-04-14 16:33 UTC, KjartanE submitted a review, later dismissed
🐱

2023-04-17 20:35 UTC, KjartanE approved these changes, later dismissed
😸

2023-04-17 21:59 UTC, curtisupshall requested changes

2023-04-17 21:59 UTC, curtisupshall commented on app/src/features/surveys/view/SurveyHeader.tsx
UI changes are outside of the scope of this ticket; this change is already implemented using the `ProjectRoleGuard`. See https://github.com/bcgov/biohubbc/pull/1000/files.

2023-04-17 21:59 UTC, curtisupshall commented on app/src/hooks/api/useProjectApi.ts
Can discard these changes as well.

2023-04-17 22:01 UTC, curtisupshall commented on api/src/paths/project/{projectId}/participants/self.ts
Should also discard this file as well, since this is only used by the frontend (see https://github.com/bcgov/biohubbc/pull/1000)

2023-04-17 23:12 UTC, NickPhura approved these changes, later dismissed

2023-04-17 23:21 UTC, curtisupshall approved these changes

2023-04-17 23:21 UTC, NickPhura approved these changes

2023-04-17 23:29 UTC, merged