SIMSBIOHUB-332
bcgov/biohubbc pull request #1168
Opened 2023-11-09 18:43 UTC by curtisupshall

## Links to Jira Tickets

- {Include a link to all applicable Jira tickets}

## Description of Changes

- {List all relevant code changes. Include any changes to the business workflow that might not be obvious to the reviewers of this PR.}

## Testing Notes

- {List any relevant testing considerations, necessary pre-reqs, and areas of the app to focus on. Specifically, include anything that will help the reviewers of this PR verify the code is functioning as expected.}

2023-11-15 19:30 UTC, al-rosenthal reviewed
We've talked about these but just writing them down here:
- when creating a record and selecting a date, the date defaults to today regardless of what I picked
- date is invalid with todays date
- it is not obvious when imported records have validation errors when saving a new record

2023-11-15 19:30 UTC, al-rosenthal commented on app/src/components/map/components/MapBaseCss.tsx
this looks like it might be a duplicate of the file at `app/src/components/map/styles`

2023-11-22 01:26 UTC, NickPhura commented
@curtisupshall 
Re validation: Noticed that if you don't select a sample site, none of the sample_* fields get highlighted red on clicking Save.

2023-11-22 01:27 UTC, al-rosenthal commented
I ran into an issue with the date validation. I can only add a record manually when I type the date in, I can't use the picker, it flags the date when I try and save it

2023-11-22 01:52 UTC, curtisupshall commented
> @curtisupshall 
> 
> Re validation: Noticed that if you don't select a sample site, none of the sample_* fields get highlighted red nor does the error status bar show up, upon clicking save.

@NickPhura This is actually expected behaviour (unless I misunderstood the business decision); a record can have all of its sampling fields left undefined, thus making it an "incidental" observation. But if one of the fields is filled in, then all of them need to be non-empty. We came to this decision after discussing the issue around importing observations in the absence of sampling data.

2023-11-23 20:12 UTC, al-rosenthal submitted a review, later dismissed
ran this locally and it looks good. The banner is nice and snappy 🐇

2023-11-24 00:55 UTC, MacQSL requested changes, later dismissed
Looks super good, and it's very responsive.
Few small things I noticed:

1. On row error the colouring of the default text for the date / time is different. Attached screenshot
2. Nit: Does it make more sense to have the Prev / Next buttons horizontal icons ie: < or >. Since it traverses the errors in the row horizontally?
3. This might be out of the scope of this ticket, but it appears there is a rendering issue with the header. When you scroll the hidden columns into view it leaves a line fragment. Attached screenshot
4. Should the cell validation errors go away as you update them ie: onChange?
![image](https://github.com/bcgov/biohubbc/assets/99926243/305b60d1-e5c2-4f5e-bc61-c704cd8a30e9)
![image](https://github.com/bcgov/biohubbc/assets/99926243/9303cc90-adde-4091-8734-d09143601b0e)

2023-11-24 00:59 UTC, NickPhura commented
@curtisupshall 
Looks good, the navigation between errors is super cool.

On the sample site form
- I was getting some duplicate key warnings. I do have a fix for it that I can push up (just adjusting the keys for the sample method/period fields).

On the observations table
- I did notice a couple warnings in the console about uncontrolled values in the observations data grid. Probably not a blocker for this PR, but something we should try and resolve if we can.

2023-11-27 17:25 UTC, curtisupshall commented
> Looks super good, and it's very responsive. Few small things I noticed:
> 
> 1. On row error the colouring of the default text for the date / time is different. Attached screenshot
> 2. Nit: Does it make more sense to have the Prev / Next buttons horizontal icons ie: < or >. Since it traverses the errors in the row horizontally?
> 3. This might be out of the scope of this ticket, but it appears there is a rendering issue with the header. When you scroll the hidden columns into view it leaves a line fragment. Attached screenshot
> 4. Should the cell validation errors go away as you update them ie: onChange?
>    ![image](https://private-user-images.githubusercontent.com/99926243/285328143-305b60d1-e5c2-4f5e-bc61-c704cd8a30e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDYxNjksIm5iZiI6MTcwMTEwNTg2OSwicGF0aCI6Ii85OTkyNjI0My8yODUzMjgxNDMtMzA1YjYwZDEtZTVjMi00ZjVlLWJjNjEtYzcwNGNkOGEzMGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE3MjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZGQ2MjlmNGYxYTI2MDkxYThkZDJmOGVjODNhMjU2YmUzOWM5NGQzMmY0ZGUyYzkwMzhmMWE0MzFkYjAxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ymMeg_l_cUk8LqVrJBUh8_W5ucB462pzMJJB-nX2BsA)
>    ![image](https://private-user-images.githubusercontent.com/99926243/285328635-9303cc90-adde-4091-8734-d09143601b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDYxNjksIm5iZiI6MTcwMTEwNTg2OSwicGF0aCI6Ii85OTkyNjI0My8yODUzMjg2MzUtOTMwM2NjOTAtYWRkZS00MDkxLTg3MzQtZDA5MTQzNjAxYjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE3MjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMWFkMTViMWFiYzYyOGZlZDNkODczZTczMjVlOGVkOTE4YTEzNzUzMjE0NDEwMzZlMWYwMmE2NzVkYWNjMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vz6EaSD1AygoL_QMQeQt8khdCrL_HTu5iyDsTvWHAmM)

I think we'll address these changes in Jer's upcoming `UI-Fixes` branch.

2023-11-27 17:25 UTC, curtisupshall commented
> @curtisupshall Looks good, the navigation between errors is super cool.
> 
> On the sample site form
> 
> * I was getting some duplicate key warnings. I do have a fix for it that I can push up (just adjusting the keys for the sample method/period fields).
> 
> On the observations table
> 
> * I did notice a couple warnings in the console about uncontrolled values in the observations data grid. Probably not a blocker for this PR, but something we should try and resolve if we can.

Resolved!

2023-11-27 20:08 UTC, al-rosenthal approved these changes
Ran this locally and it looks great! 🍔

2023-11-27 23:54 UTC, MacQSL approved these changes
Love it!

2023-11-27 23:58 UTC, merged