BHBC 968/967 - Enhance file upload end-points
bcgov/biohubbc pull request #214
Opened 2021-04-08 23:31 UTC by sdevalapurkar

# Overview

## Links to jira tickets

- https://quartech.atlassian.net/browse/BHBC-967
- https://quartech.atlassian.net/browse/BHBC-968

## This PR contains the following changes

- End to end upload flow with list view, ability to delete individual files, view them in list, and also view their data using a signed url

## This PR contains the following types of changes

- [x] New feature (change which adds functionality)
- [x] Enhancement (improvements to existing functionality)

## How Has This Been Tested?

- Local, S3, database

## Screenshots

<img width="1042" alt="1" src="https://user-images.githubusercontent.com/28017034/114108390-dbc41600-9887-11eb-8faf-f6906cb89925.png">
<img width="1039" alt="2" src="https://user-images.githubusercontent.com/28017034/114108392-dcf54300-9887-11eb-9401-685cffa7544e.png">

2021-04-08 23:51 UTC, sdevalapurkar commented
No tests in this PR - all tests coming in separate pull request 👼🏼

2021-04-09 17:02 UTC, anissa-agahchen requested changes
If a file is re-uploaded, the date needs to be modified to the latest date.

2021-04-09 19:51 UTC, anissa-agahchen approved these changes

2021-04-09 19:51 UTC, anissa-agahchen commented on api/src/paths/project/{projectId}/attachments/upload.ts
> +          upsertProjectAttachment(file, Number(req.params.projectId), connection)
nice!

2021-04-09 19:52 UTC, merged