Techdebt temp
bcgov/biohubbc pull request #741
Opened 2022-04-19 20:48 UTC by anissa-agahchen

# Overview

## Links to jira tickets

- {Include links to all of the applicable Jira tickets}

## This PR contains the following changes

- {List all the relevant changes. If there are many changes across many Jira tickets, organize the changes by Jira ticket}

## This PR contains the following types of changes

- [ ] New feature (change which adds functionality)
- [ ] Enhancement (improvements to existing functionality)
- [ ] Bug fix (change which fixes an issue)
- [ ] Misc cleanup / Refactoring / Documentation
- [ ] Version change

## Checklist

A list of items that are good to consider when making any changes.

_Note: this list is not exhaustive, and not all items are always applicable._

### General

- [ ] I have performed a self-review of my own code

### Code

- [ ] New files/classes/functions have appropriately descriptive names and comment blocks to describe their use/behaviour
- [ ] I have avoided duplicating code when possible, moving re-usable pieces into functions
- [ ] I have avoided hard-coding values where possible and moved any re-usable constants to a constants file
- [ ] My code is as flat as possible (avoids deeply nested if/else blocks, promise chains, etc)
- [ ] My code changes account for null/undefined values and handle errors appropriately
- [ ] My code uses types/interfaces to help describe values/parameters/etc, help ensure type safety, and improve readability

### Style

- [ ] My code follows the established style conventions
- [ ] My code uses native material-ui components/icons/conventions when possible

### Documentation

- [ ] I have commented my code sufficiently, such that an unfamiliar developer could understand my code
- [ ] I have added/updated README's and related documentation, as needed

### Tests

- [ ] I have added/updated unit tests for any code I've added/updated
- [ ] I have added/updated the Postman requests/tests to account for any API endpoints I've added/updated

### Linting/Formatting

- [ ] I have run the linter and fixed any issues, as needed  
       _See the `lint` commands in package.json_
- [ ] I have run the formatter and fixed any issues, as needed  
       _See the `format` commands in package.json_

### SonarCloud

- [ ] I have addressed all SonarCloud Bugs, Vulnerabilities, Security Hotspots, and Code Smells

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Screenshots

Please add any relevant UI screenshots, if applicable.

2022-04-19 20:53 UTC, NickPhura commented on api/src/paths/public/project/{projectId}/view.ts
> +      console.log('result is: ', result);
💬

2022-04-20 20:52 UTC, NickPhura approved these changes

2022-04-20 20:55 UTC, NickPhura commented
Just noticing 1 issue with the public view:
![image](https://user-images.githubusercontent.com/903781/164321210-8fecdec8-ddb2-4863-8c61-097fab82a83e.png)

vs the admin view:
![image](https://user-images.githubusercontent.com/903781/164321252-92848d07-0996-4955-a0cc-eb6d936a71c0.png)

2022-04-20 22:45 UTC, NickPhura requested changes
See my other comment (forgot to write it here originally)

2022-04-22 00:08 UTC, NickPhura commented
> Just noticing 1 issue with the public view: ![image](https://user-images.githubusercontent.com/903781/164321210-8fecdec8-ddb2-4863-8c61-097fab82a83e.png)
> 
> vs the admin view: ![image](https://user-images.githubusercontent.com/903781/164321252-92848d07-0996-4955-a0cc-eb6d936a71c0.png)
> 
> Activities and Project Type aren't rendering correctly on the public page.
> 
> Looks like the response from the API is returning the wrong values for those 2 fields: ![image](https://user-images.githubusercontent.com/903781/164321577-853a4ce1-fe95-4c58-bdfe-5c01bb2b23af.png)

Pushed up a commit to address this

2022-04-22 00:09 UTC, NickPhura submitted a review, later dismissed

2022-04-22 15:44 UTC, anissa-agahchen commented
@NickPhura, thank you for the fix.

2022-04-22 19:51 UTC, KjartanE approved these changes
Looks good!

2022-04-22 22:16 UTC, merged