BHBC-1930, 1931
bcgov/biohubbc pull request #820
Opened 2022-09-19 21:52 UTC by AlfredRosenthal

# Overview

## Links to Jira tickets

[BHBC-1930](https://quartech.atlassian.net/browse/BHBC-1930?atlOrigin=eyJpIjoiNzdmOTY0NDljNWIzNGJmZmE3ZGVkYWVhOWFlMGQ2NzciLCJwIjoiaiJ9)

[BHBC-1931](https://quartech.atlassian.net/browse/BHBC-1931?atlOrigin=eyJpIjoiYWMwYWUzMTA0MTQ2NGQ2MjkxYzU3YjRiMmQyNDIwZGMiLCJwIjoiaiJ9)

## Description of relevant changes

- Added SRB and Non SRB Elk templates to resource page
- Added SRB and non SRB validation migrations

## PR Checklist

A list of items that are good to consider when making any changes.

_Note: this list is not exhaustive, and not all items are always applicable._

### Code

- [ ] New files/classes/functions have appropriately descriptive names and comment blocks to describe their use/behaviour
- [ ] I have avoided duplicating code when possible, moving re-usable pieces into functions
- [ ] I have avoided hard-coding values where possible and moved any re-usable constants to a constants file
- [ ] My code is as flat as possible (avoids deeply nested if/else blocks, promise chains, etc)
- [ ] My code changes account for null/undefined values and handle errors appropriately
- [ ] My code uses types/interfaces to help describe values/parameters/etc, help ensure type safety, and improve readability

### Style

- [ ] My code follows the established style conventions
- [ ] My code uses native material-ui components/icons/conventions when possible

### Documentation

- [ ] I have commented my code sufficiently, such that an unfamiliar developer could understand my code
- [ ] I have added/updated README's and related documentation, as needed

### Tests

- [ ] I have added/updated unit tests for any code I've added/updated
- [ ] I have added/updated the Postman requests/tests to account for any API endpoints I've added/updated

### Linting/Formatting

- [ ] I have run the linter and fixed any issues, as needed  
       _See the `lint` commands in package.json_
- [ ] I have run the formatter and fixed any issues, as needed  
       _See the `format` commands in package.json_

### SonarCloud

- [ ] I have addressed all SonarCloud Bugs, Vulnerabilities, Security Hotspots, and Code Smells

2022-09-20 21:21 UTC, curtisupshall requested changes

2022-09-20 21:21 UTC, curtisupshall commented on database/src/migrations/template_methodology_species_validations/elk_non_srb_survey.ts
> +      name: 'MArked Animals',
Typo.

2022-09-20 21:21 UTC, curtisupshall commented on database/src/migrations/template_methodology_species_validations/picklist_variables/v0.2.ts
> +  { name: 'Cutblock - Matrue' },
Should this read `'Cutblock - Mature'`?

2022-09-22 15:17 UTC, AlfredRosenthal commented on database/src/migrations/template_methodology_species_validations/elk_non_srb_survey.ts
> +      name: 'MArked Animals',
good catch, fixed.

2022-09-22 15:18 UTC, AlfredRosenthal commented on database/src/migrations/template_methodology_species_validations/picklist_variables/v0.2.ts
> +  { name: 'Cutblock - Matrue' },
fixed

2022-09-23 19:10 UTC, KjartanE approved these changes
🥇 Looks great

2022-09-23 19:11 UTC, curtisupshall approved these changes

2022-09-23 19:55 UTC, merged