BHBC-2076: Display Templates from S3
bcgov/biohubbc pull request #910
Opened 2023-01-11 23:32 UTC by curtisupshall

# Overview
Render live S3 bucket contents on the Resources page.

## Links to Jira tickets

 - https://quartech.atlassian.net/browse/BHBC-2076

## Description of relevant changes

- {List all relevant changes, in particular anything that will help the reviewers test/verify this PR}

## PR Checklist

A list of items that are good to consider when making any changes.

_Note: this list is not exhaustive, and not all items are always applicable._

### Code

- [ ] New files/classes/functions have appropriately descriptive names and comment blocks to describe their use/behaviour
- [ ] I have avoided duplicating code when possible, moving re-usable pieces into functions
- [ ] I have avoided hard-coding values where possible and moved any re-usable constants to a constants file
- [ ] My code is as flat as possible (avoids deeply nested if/else blocks, promise chains, etc)
- [ ] My code changes account for null/undefined values and handle errors appropriately
- [ ] My code uses types/interfaces to help describe values/parameters/etc, help ensure type safety, and improve readability

### Style

- [ ] My code follows the established style conventions
- [ ] My code uses native material-ui components/icons/conventions when possible

### Documentation

- [ ] I have commented my code sufficiently, such that an unfamiliar developer could understand my code
- [ ] I have added/updated README's and related documentation, as needed

### Tests

- [ ] I have added/updated unit tests for any code I've added/updated
- [ ] I have added/updated the Postman requests/tests to account for any API endpoints I've added/updated

### Linting/Formatting

- [ ] I have run the linter and fixed any issues, as needed  
       _See the `lint` commands in package.json_
- [ ] I have run the formatter and fixed any issues, as needed  
       _See the `format` commands in package.json_

### SonarCloud

- [ ] I have addressed all SonarCloud Bugs, Vulnerabilities, Security Hotspots, and Code Smells

2023-01-13 00:04 UTC, KjartanE submitted a review, later dismissed
🎮

2023-01-13 23:20 UTC, NickPhura requested changes
Was trying it in Openshfit, and the download button for a resource doesn't seem to work. The page refreshes and I get kicked back the the project list page, and no file is downloaded.

If I copy the url from the download button and paste it into my browser, then it does download the file, but clicking the button doesn't seem to work for me.

(Same behaviour in Firefox, Chrome and Edge)

2023-01-14 00:33 UTC, curtisupshall commented
> Was trying it in Openshfit, and the download button for a resource doesn't seem to work. The page refreshes and I get kicked back the the project list page, and no file is downloaded.
> 
> If I copy the url from the download button and paste it into my browser, then it does download the file, but clicking the button doesn't seem to work for me.
> 
> (Same behaviour in Firefox, Chrome and Edge)

Good catch! Fixed with https://github.com/bcgov/biohubbc/pull/910/commits/03a6bc3d4205bd0669d6be3067c83aae38ec9ddc.

2023-01-16 19:56 UTC, NickPhura submitted a review, later dismissed

2023-01-16 21:53 UTC, NickPhura approved these changes

2023-01-16 21:55 UTC, merged